name: Workflow Immortality

on:
  schedule:
    # run once a month on the first day of the month at 00:20 UTC
    - cron: '20 0 1 * *'
  workflow_dispatch: {}

jobs:
  keepalive:
    name: Keep Workflow Alive
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Keep cronjob based triggers of GitHub workflows alive
        uses: PhrozenByte/gh-workflow-immortality@v1
        with:
          secret: ${{ secrets.PAT_ACTION_RW }}
          repos: ${{ github.repository }}

  clean-runs:
    name: Clean Old Runs
    needs: keepalive
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Clean old runs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          WORKFLOW_NAME=$(basename "${GITHUB_WORKFLOW_REF%%@*}")
          RUNS=$(gh run list \
            --repo "${{ github.repository }}" \
            --workflow "$WORKFLOW_NAME" \
            --limit 2000 \
            --json databaseId,conclusion \
            --jq '.[] | select(.conclusion != null and .conclusion != "") | .databaseId')

          for RUN in $RUNS; do
            if [[ $RUN == "${{ github.run_id }}" ]]; then
              continue
            fi
            echo "Deleting run $RUN"
            gh run delete "$RUN" \
              --repo "${{ github.repository }}"
            sleep 0.1
          done
